containers:
  - name: "amd64-alpine-wasi-bun"
    arch: "amd64"
    target: "wasi"
    dockerfile: |
      FROM alpine:3.17
      RUN apk add --no-cache curl bash
      RUN curl -fsSL https://bun.sh/install | bash
      ENV BUN_INSTALL="/root/.bun"
      ENV PATH="${BUN_INSTALL}/bin:${PATH}"
      CMD ["bash"]
